# Generated by Django 3.2.17 on 2023-03-21 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('customer_type', models.IntegerField(choices=[(0, 'student'), (1, 'teacher'), (2, 'manager')], default=0, verbose_name='accountType')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updateTime')),
            ],
        ),
    ]
