# Generated by Django 3.2.17 on 2023-03-21 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.BigIntegerField(verbose_name='studentID')),
                ('name', models.CharField(max_length=255, verbose_name='studentName')),
                ('sex', models.CharField(max_length=10, verbose_name='Gender')),
                ('birth_day', models.CharField(max_length=255, verbose_name='birthDate')),
                ('native_place', models.CharField(max_length=255, verbose_name='hometown')),
                ('major', models.CharField(max_length=255, verbose_name='major')),
                ('clazz', models.CharField(max_length=255, verbose_name='class')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updateTime')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='userID')),
            ],
        ),
    ]
