# Generated by Django 3.2.17 on 2023-03-21 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='className')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updateTime')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherinfo')),
            ],
            options={
                'unique_together': {('name', 'teacher_id')},
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('major_code', models.CharField(max_length=32, unique=True, verbose_name='majotCode')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='majorName')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updateTime')),
            ],
        ),
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='className')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updateTime')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.major')),
            ],
            options={
                'unique_together': {('name', 'major_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentCurriculumScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=1, max_digits=10)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updateTime')),
                ('curriculum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.curriculum')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
            options={
                'unique_together': {('student_id', 'curriculum_id')},
            },
        ),
        migrations.CreateModel(
            name='SchoolTimeTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clazz_week', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], max_length=32, verbose_name='classWeek')),
                ('clazz_time', models.CharField(choices=[(1, '8:00~9:40'), (2, '10:00~11:40'), (3, '14:00~15:40'), (4, '15:50~17:50')], max_length=32, verbose_name='classTime')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updateTime')),
                ('clazz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.clazz')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.curriculum')),
            ],
            options={
                'unique_together': {('clazz_week', 'clazz_time', 'clazz_id')},
            },
        ),
        migrations.CreateModel(
            name='ClazzStudents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createTime')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updateTime')),
                ('clazz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.clazz')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
            options={
                'unique_together': {('student_id', 'clazz_id')},
            },
        ),
    ]
